name: Fix MIME type for GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Fix MIME types in built files
      run: |
        # 确保所有JS文件都有正确的MIME类型
        find dist -name "*.js" -exec sh -c 'echo "// MIME type fix" > "$1.tmp" && cat "$1" >> "$1.tmp" && mv "$1.tmp" "$1"' _ {} \;
        
        # 修改index.html中的脚本引用
        sed -i 's|type="module"|type="module" crossorigin=""|g' dist/index.html
        
        # 创建.htaccess文件用于Apache服务器
        echo '<IfModule mod_mime.c>' > dist/.htaccess
        echo '  AddType application/javascript .js' >> dist/.htaccess
        echo '  AddType application/wasm .wasm' >> dist/.htaccess
        echo '</IfModule>' >> dist/.htaccess
        
        # 创建_nojekyll文件防止Jekyll处理
        touch dist/.nojekyll
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist